apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  annotations:
    github.com/project-slug: Femi-lawal/${{ values.name }}
    prometheus.io/scrape: "true"
    prometheus.io/port: "${{ values.port }}"
  tags:
    - go
    - backend
spec:
  type: service
  lifecycle: production
  owner: ${{ values.owner }}
  system: neobank-platform
